import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import fs from 'fs/promises';
import path from 'path';
import { handleUpload } from './upload'
import { encrypt } from './handleToken';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 800,
    show: false,
    resizable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    mainWindow.focus();
  });

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

ipcMain.on('app-loaded', async (event) => {
  try {
    let isToken = true;
    try {
      const filepath = path.join(app.getPath('userData'), 'token.txt');
      await fs.readFile(filepath, 'utf-8');
    } catch {
      isToken = false;
    }
    const browserWindow = BrowserWindow.fromWebContents(event.sender);
    browserWindow.webContents.send('token-check', { isToken });
  } catch (error) {
    handleError(error);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.on('store-token', async (event, token) => {
  try {
    const result = await encrypt(token);
    const browserWindow = BrowserWindow.fromWebContents(event.sender);
    browserWindow.webContents.send('token-updated', result);
  } catch (error) {
    handleError(error);
  }
});

ipcMain.on('show-open-file-dialog', (event, dst: boolean) => {
  try {
    const browserWindow = BrowserWindow.fromWebContents(event.sender);
    if (!browserWindow) return;
    showFileOpenDialog(browserWindow, dst);
  } catch (error) {
    handleError(error);
  }
});

const showFileOpenDialog = async (browserWindow: BrowserWindow, dst: boolean) => {
  try {
    const result = await dialog.showOpenDialog(browserWindow, {
      properties: ['openFile'],
      filters: [{ name: 'CSV file', extensions: ['csv', 'CSV'] }]
    });
  
    if (result.canceled) {
      browserWindow.webContents.send('upload-canceled');
      return
    }
  
    const [filepath] = result.filePaths;
  
    const uploadResult = await handleUpload(filepath, dst, browserWindow);
    browserWindow.webContents.send('upload-done', uploadResult);
  } catch (error) {
    handleError(error);
  }
}

function handleError(error: Error) {
  let message = `${error.message}\n${error.stack}`;
  dialog.showErrorBox(error.name, message);
}

process.on('uncaughtException', (error) => {
  handleError(error);
});

process.on('unhandledRejection', (reason) => {
  let message;
  let stack;
  if (reason instanceof Error) {
    message = reason.message;
    stack = reason.stack;
  } else {
    try {
      message = JSON.stringify(reason);
    } catch {
      message = String(reason);
    }
    stack = new Error().stack;
  }

  const allMessage = `${message}\n\nStack Trace:\n${stack}`; 
  dialog.showErrorBox('Unhandled Promise Rejection', allMessage);
});
